# ---------------------------------------------------------------------------
# VENDORED REFERENCE — NOT EXECUTED BY THE APPLICATION.
#
# The original Colab export this integration was built from, kept so the
# provenance of the pipeline is auditable. It is Colab-specific (Drive mounts,
# shell magics) and will not run outside that environment.
#
# Drive paths and the source notebook URL have been redacted for publication.
# The production implementation lives in engine/ and models/ — see
# docs/MODELS.md and docs/IMPLEMENTATION.md.
# ---------------------------------------------------------------------------
# -*- coding: utf-8 -*-
"""cctv_pipeline_inference.ipynb

Automatically generated by Colab.

Original file is located at
    <private Colab notebook — URL redacted>

# ITSO - Segment + Inference Pipeline

Takes a raw CCTV video, splits it into 15s segments, and runs both trained models on each segment:

- **Stage 2** - R3D-18 action recognition (14 classes)
- **Stage 3 Track 1** - YOLOv8s suspicious-object detector (Gun, Knife, Rifle, Fire, Smoke, Unattended_Bag, Mask, Broken_Glass)
- **Stage 3 Track 2** - stock COCO-pretrained YOLOv8 for context objects (person, bag, vehicle) - no training needed

Output: one structured record per 15s segment (action label + confidence, Track 1 detections, Track 2 detections), saved to JSON - this is what the fusion/scoring stage (not built yet) will consume.

**This notebook does NOT do fusion/scoring yet** - that decides High/Normal/Low importance and comes after this.

## Step 0 - Mount Drive, configure paths
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# ============================================================
# EDIT ME
# ============================================================
STAGE2_CHECKPOINT = '<DRIVE>/CCTV_Dataset/model_output/r3d18_best.pt'
STAGE3_WEIGHTS = '<DRIVE>/ITSO_ObjectDetection/.../weights/best.pt'
INPUT_VIDEO_PATH = '<DRIVE>/ITSO_ObjectDetection/sample.mp4'  # <- a CCTV video to test on
OUTPUT_DIR = '<DRIVE>/ITSO_Pipeline/pipeline_output'
SEGMENT_SECONDS = 15

os.makedirs(OUTPUT_DIR, exist_ok=True)
for p in [STAGE2_CHECKPOINT, STAGE3_WEIGHTS, INPUT_VIDEO_PATH]:
    print(('[found] ' if os.path.exists(p) else '[MISSING] ') + p)

"""## Step 1 - Install dependencies"""

!pip -q install ultralytics
import torch, torchvision
print('torch', torch.__version__, '| CUDA available:', torch.cuda.is_available())
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using device:', device)

"""## Step 2 - Load Stage 2 (action recognition) model

This handles both common checkpoint formats: a plain `state_dict`, or a dict wrapping it under a key like `model_state_dict` / `state_dict`. It tries the plain load first, then falls back to unwrapping.

**Edit `ACTION_CLASSES` if this order doesn't match what your dataset-builder notebook used** (check that notebook's class folder order - it's normally alphabetical if you used `ImageFolder`-style loading).
"""

from torchvision.models.video import r3d_18
import torch.nn as nn

# ============================================================
# EDIT ME if this order differs from your Stage 2 training run
# ============================================================
ACTION_CLASSES = [
    'Abuse', 'Arrest', 'Arson', 'Assault', 'Burglary', 'Explosion', 'Fighting',
    'Normal', 'RoadAccidents', 'Robbery', 'Shooting', 'Shoplifting', 'Stealing', 'Vandalism',
]

def load_stage2_model(checkpoint_path, num_classes, device):
    model = r3d_18(weights=None)
    model.fc = nn.Linear(model.fc.in_features, num_classes)

    raw = torch.load(checkpoint_path, map_location=device)

    # figure out where the actual state_dict is hiding
    if isinstance(raw, dict) and any(k in raw for k in ('model_state_dict', 'state_dict')):
        state_dict = raw.get('model_state_dict', raw.get('state_dict'))
        print('Loaded from wrapped checkpoint dict. Keys present:', list(raw.keys()))
    elif isinstance(raw, dict):
        # looks like a raw state_dict already (keys are layer names)
        state_dict = raw
        print('Loaded as raw state_dict.')
    else:
        raise ValueError(f'Unrecognized checkpoint format: {type(raw)}')

    # strip a 'module.' prefix if the model was saved from nn.DataParallel
    state_dict = { (k[7:] if k.startswith('module.') else k): v for k, v in state_dict.items() }

    missing, unexpected = model.load_state_dict(state_dict, strict=False)
    if missing:
        print('WARNING - missing keys when loading:', missing)
    if unexpected:
        print('WARNING - unexpected keys when loading:', unexpected)

    model.to(device).eval()
    return model

stage2_model = load_stage2_model(STAGE2_CHECKPOINT, len(ACTION_CLASSES), device)
print('Stage 2 model loaded.')

"""## Step 3 - Load Stage 3 Track 1 (custom suspicious-object detector) and Track 2 (COCO context)"""

from ultralytics import YOLO

track1_model = YOLO(STAGE3_WEIGHTS)
print('Track 1 classes:', track1_model.names)

track2_model = YOLO('yolov8s.pt')  # stock COCO-pretrained, downloads automatically if not cached

# Only keep these COCO classes as "context" - everything else from track2 is ignored
TRACK2_KEEP_CLASSES = {'person', 'backpack', 'handbag', 'suitcase', 'car', 'motorcycle', 'bicycle'}
track2_class_ids = {i for i, name in track2_model.names.items() if name in TRACK2_KEEP_CLASSES}
print('Track 2 context classes kept:', TRACK2_KEEP_CLASSES)

"""## Step 4 - Video segmentation helper

Reads the video once with OpenCV and computes frame-index ranges for each 15s segment, based on the video's own FPS - no re-encoding or temp files needed.
"""

import cv2

def get_segment_frame_ranges(video_path, segment_seconds):
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()

    frames_per_segment = int(round(fps * segment_seconds))
    ranges = []
    start = 0
    while start < total_frames:
        end = min(start + frames_per_segment, total_frames)
        ranges.append((start, end))
        start = end
    return ranges, fps

segment_ranges, video_fps = get_segment_frame_ranges(INPUT_VIDEO_PATH, SEGMENT_SECONDS)
print(f'Video FPS: {video_fps:.2f}')
print(f'{len(segment_ranges)} segments of ~{SEGMENT_SECONDS}s each')

"""## Step 5 - Frame sampling utilities

- Action recognition needs exactly **16 uniformly-spaced frames** per segment (matching Stage 2 training), resized/cropped to 112x112 and normalized with Kinetics stats.
- Object detection (Track 1 and Track 2) samples **1 frame per second** within the segment - running YOLO on every single frame is unnecessary and slow; suspicious objects/context don't change that fast.
"""

import numpy as np
import torch.nn.functional as F

# Kinetics-400 normalization stats (matches Stage 2 training preprocessing)
KINETICS_MEAN = [0.43216, 0.394666, 0.37645]
KINETICS_STD = [0.22803, 0.22145, 0.216989]

def read_frames(video_path, frame_indices):
    cap = cv2.VideoCapture(video_path)
    frames = {}
    for idx in sorted(set(frame_indices)):
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ok, frame = cap.read()
        if ok:
            frames[idx] = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    cap.release()
    return frames

def sample_action_recognition_clip(video_path, start_frame, end_frame, num_frames=16):
    indices = np.linspace(start_frame, end_frame - 1, num_frames).astype(int)
    frames = read_frames(video_path, indices)
    clip = []
    for idx in indices:
        frame = frames.get(idx)
        if frame is None:
            continue
        frame = cv2.resize(frame, (128, 128))
        h, w, _ = frame.shape
        top, left = (h - 112) // 2, (w - 112) // 2
        frame = frame[top:top + 112, left:left + 112]
        clip.append(frame)
    if len(clip) < num_frames:
        # pad by repeating the last available frame (rare - only if reads failed near the end)
        while len(clip) < num_frames and clip:
            clip.append(clip[-1])
    clip = np.stack(clip).astype(np.float32) / 255.0          # (T, H, W, C)
    clip = torch.from_numpy(clip).permute(3, 0, 1, 2)          # (C, T, H, W)
    mean = torch.tensor(KINETICS_MEAN).view(3, 1, 1, 1)
    std = torch.tensor(KINETICS_STD).view(3, 1, 1, 1)
    clip = (clip - mean) / std
    return clip.unsqueeze(0)  # (1, C, T, H, W)

def sample_detection_frames(video_path, start_frame, end_frame, fps, stride_seconds=1.0):
    stride_frames = max(1, int(round(fps * stride_seconds)))
    indices = list(range(start_frame, end_frame, stride_frames))
    return read_frames(video_path, indices)

"""## Step 6 - Per-segment inference

For each segment:
1. Run Stage 2 on the 16-frame clip -> top-1 action label + confidence.
2. Run Track 1 on ~1 fps sampled frames -> per-class max confidence + how many sampled frames it appeared in.
3. Run Track 2 the same way, filtered to context classes only.
"""

def aggregate_detections(model, frames_dict, keep_class_ids=None, conf_threshold=0.35):
    agg = {}  # class_name -> {'max_conf': float, 'frame_hits': int}
    for frame in frames_dict.values():
        results = model.predict(frame, conf=conf_threshold, verbose=False)[0]
        seen_this_frame = set()
        for box in results.boxes:
            cls_id = int(box.cls.item())
            if keep_class_ids is not None and cls_id not in keep_class_ids:
                continue
            cls_name = model.names[cls_id]
            conf = float(box.conf.item())
            entry = agg.setdefault(cls_name, {'max_conf': 0.0, 'frame_hits': 0})
            entry['max_conf'] = max(entry['max_conf'], conf)
            seen_this_frame.add(cls_name)
        for cls_name in seen_this_frame:
            agg[cls_name]['frame_hits'] += 1
    return agg

def run_segment(video_path, start_frame, end_frame, fps):
    # Stage 2 - action recognition
    clip = sample_action_recognition_clip(video_path, start_frame, end_frame).to(device)
    with torch.no_grad():
        logits = stage2_model(clip)
        probs = torch.softmax(logits, dim=1)[0]
        top_idx = int(torch.argmax(probs).item())

    # Sample frames once, reuse for both detectors
    det_frames = sample_detection_frames(video_path, start_frame, end_frame, fps)

    track1_dets = aggregate_detections(track1_model, det_frames)
    track2_dets = aggregate_detections(track2_model, det_frames, keep_class_ids=track2_class_ids)

    return {
        'action_label': ACTION_CLASSES[top_idx],
        'action_confidence': round(float(probs[top_idx]), 4),
        'track1_detections': track1_dets,
        'track2_detections': track2_dets,
    }

"""## Step 7 - Run the pipeline over every segment"""

import subprocess

REENCODED_PATH = '/content/video2_h264.mp4'

subprocess.run([
    'ffmpeg', '-y', '-i', INPUT_VIDEO_PATH,
    '-c:v', 'libx264', '-preset', 'fast', '-crf', '23',
    '-c:a', 'aac',
    REENCODED_PATH
], check=True)

print('Re-encoded to:', REENCODED_PATH)

cap = cv2.VideoCapture(REENCODED_PATH)
print('isOpened:', cap.isOpened())
ok, frame = cap.read()
print('First read ok:', ok)
if ok:
    print('Frame shape:', frame.shape)
cap.release()

import cv2
import numpy as np
import torch.nn.functional as F
import time

# --- Self-check before doing anything else ---
INPUT_VIDEO_PATH = REENCODED_PATH   # force it here, no reliance on earlier cells
print('Using INPUT_VIDEO_PATH:', INPUT_VIDEO_PATH)

_check_cap = cv2.VideoCapture(INPUT_VIDEO_PATH)
print('isOpened:', _check_cap.isOpened())
_ok, _frame = _check_cap.read()
print('First read ok:', _ok)
_check_cap.release()
if not _ok:
    raise RuntimeError('Video still not readable - stop here and tell me, do not proceed further.')

KINETICS_MEAN = [0.43216, 0.394666, 0.37645]
KINETICS_STD = [0.22803, 0.22145, 0.216989]

def preprocess_action_frame(frame_rgb):
    frame = cv2.resize(frame_rgb, (128, 128))
    top, left = (128 - 112) // 2, (128 - 112) // 2
    return frame[top:top + 112, left:left + 112]

def build_action_clip(buffer_frames, num_frames=16):
    if not buffer_frames:
        return None
    indices = np.linspace(0, len(buffer_frames) - 1, num_frames).astype(int)
    clip = [preprocess_action_frame(buffer_frames[i]) for i in indices]
    clip = np.stack(clip).astype(np.float32) / 255.0
    clip = torch.from_numpy(clip).permute(3, 0, 1, 2)
    mean = torch.tensor(KINETICS_MEAN).view(3, 1, 1, 1)
    std = torch.tensor(KINETICS_STD).view(3, 1, 1, 1)
    clip = (clip - mean) / std
    return clip.unsqueeze(0)

def aggregate_detections(model, frames_list, keep_class_ids=None, conf_threshold=0.35):
    agg = {}
    for frame in frames_list:
        results = model.predict(frame, conf=conf_threshold, verbose=False)[0]
        seen_this_frame = set()
        for box in results.boxes:
            cls_id = int(box.cls.item())
            if keep_class_ids is not None and cls_id not in keep_class_ids:
                continue
            cls_name = model.names[cls_id]
            conf = float(box.conf.item())
            entry = agg.setdefault(cls_name, {'max_conf': 0.0, 'frame_hits': 0})
            entry['max_conf'] = max(entry['max_conf'], conf)
            seen_this_frame.add(cls_name)
        for cls_name in seen_this_frame:
            agg[cls_name]['frame_hits'] += 1
    return agg

def run_segment_from_buffer(buffer_frames, fps, detection_stride_seconds=1.0):
    clip = build_action_clip(buffer_frames).to(device)
    with torch.no_grad():
        logits = stage2_model(clip)
        probs = torch.softmax(logits, dim=1)[0]
        top_idx = int(torch.argmax(probs).item())

    stride = max(1, int(round(fps * detection_stride_seconds)))
    det_frames = buffer_frames[::stride]

    track1_dets = aggregate_detections(track1_model, det_frames)
    track2_dets = aggregate_detections(track2_model, det_frames, keep_class_ids=track2_class_ids)

    return {
        'action_label': ACTION_CLASSES[top_idx],
        'action_confidence': round(float(probs[top_idx]), 4),
        'track1_detections': track1_dets,
        'track2_detections': track2_dets,
    }

# ---- Single sequential pass over the whole video ----
cap = cv2.VideoCapture(INPUT_VIDEO_PATH)
frames_per_segment = int(round(video_fps * SEGMENT_SECONDS))
print('Frames per segment:', frames_per_segment, '| video_fps:', video_fps, '| SEGMENT_SECONDS:', SEGMENT_SECONDS)

results = []
buffer = []
frame_idx = 0
segment_start_frame = 0
segment_idx = 0

while True:
    ok, frame = cap.read()
    if not ok:
        break
    buffer.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    frame_idx += 1

    if len(buffer) >= frames_per_segment:
        t0 = time.time()
        segment_result = run_segment_from_buffer(buffer, video_fps)
        segment_result.update({
            'segment_index': segment_idx,
            'start_time_sec': round(segment_start_frame / video_fps, 2),
            'end_time_sec': round(frame_idx / video_fps, 2),
        })
        results.append(segment_result)
        print(f"Segment {segment_idx:3d} [{segment_result['start_time_sec']:6.1f}s-{segment_result['end_time_sec']:6.1f}s] "
              f"-> {segment_result['action_label']} ({segment_result['action_confidence']:.2f}) "
              f"| T1: {list(segment_result['track1_detections'].keys())} "
              f"| T2: {list(segment_result['track2_detections'].keys())} "
              f"[{time.time()-t0:.1f}s]")
        segment_idx += 1
        segment_start_frame = frame_idx
        buffer = []

if buffer:
    t0 = time.time()
    segment_result = run_segment_from_buffer(buffer, video_fps)
    segment_result.update({
        'segment_index': segment_idx,
        'start_time_sec': round(segment_start_frame / video_fps, 2),
        'end_time_sec': round(frame_idx / video_fps, 2),
    })
    results.append(segment_result)
    print(f"Segment {segment_idx:3d} (final, partial) [{segment_result['start_time_sec']:6.1f}s-{segment_result['end_time_sec']:6.1f}s] "
          f"-> {segment_result['action_label']} ({segment_result['action_confidence']:.2f}) [{time.time()-t0:.1f}s]")

cap.release()
print(f'\nDone - {len(results)} segments processed.')

"""## Step 8 - Save results to Drive"""

import json
from datetime import datetime

video_name = os.path.splitext(os.path.basename(INPUT_VIDEO_PATH))[0]
out_path = os.path.join(OUTPUT_DIR, f'{video_name}_segments.json')

with open(out_path, 'w') as f:
    json.dump({
        'video': INPUT_VIDEO_PATH,
        'segment_seconds': SEGMENT_SECONDS,
        'generated_at': datetime.now().isoformat(),
        'segments': results,
    }, f, indent=2)

print('Saved:', out_path)

import cv2

cap = cv2.VideoCapture(INPUT_VIDEO_PATH)
print('Opened:', cap.isOpened())
print('FPS:', cap.get(cv2.CAP_PROP_FPS))
print('Frame count:', cap.get(cv2.CAP_PROP_FRAME_COUNT))
print('Width x Height:', cap.get(cv2.CAP_PROP_FRAME_WIDTH), 'x', cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
cap.release()

import os
print('\\nFile exists:', os.path.exists(INPUT_VIDEO_PATH))
print('File size (MB):', os.path.getsize(INPUT_VIDEO_PATH) / 1e6 if os.path.exists(INPUT_VIDEO_PATH) else 'N/A')

"""## Done - what you have

A JSON file with one record per 15s segment: action label + confidence, Track 1 suspicious-object detections (with max confidence and how many sampled frames each class appeared in), and Track 2 context-object detections in the same format.

**Example record shape:**
```json
{
  "segment_index": 3,
  "start_time_sec": 45.0,
  "end_time_sec": 60.0,
  "action_label": "Fighting",
  "action_confidence": 0.87,
  "track1_detections": {"Knife": {"max_conf": 0.61, "frame_hits": 4}},
  "track2_detections": {"person": {"max_conf": 0.95, "frame_hits": 15}}
}
```

**Next:** design the fusion/scoring stage that reads this JSON and decides a significance score + High/Normal/Low importance per segment - e.g. `Fighting` + a detected `Knife` + multiple `person` hits is a strong candidate for High, while `Normal` action with no Track 1 detections is Low.

"""